                  {loca: 'af',name: 'Afrikaans (Afrikaans)',flag: ' '},
                  {loca: 'ar',name: 'Arabic (اللغة العربية)',flag: ' '},
                  {loca: 'az',name: 'Azerbaijani (Azərbaycan)',flag: ' '},
                  {loca: 'bg',name: 'Bulgarian (български)',flag: ' '},
                  {loca: 'ca',name: 'Catalan (català)',flag: ' '},
                  {loca: 'ckb',name: 'Central Kurdish (کوردی)',flag: ' '},
                  {loca: 'cs',name: 'Czech (čeština)',flag: ' '},
                  {loca: 'de',name: 'German (Deutsch)',flag: ' '},
                  {loca: 'el',name: 'Greek (Ελληνικά)',flag: ' '},
                  {loca: 'en',name: 'English',flag: ' '},
                  {loca: 'es',name: 'Spanish (Español)',flag: ' '},
                  {loca: 'et',name: 'Estonian (eesti)',flag: ' '},
                  {loca: 'fa',name: 'Persian (فارسی)',flag: ' '},
                  {loca: 'fi',name: 'Finnish (suomi)',flag: ' '},
                  {loca: 'fr',name: 'French (Français)',flag: ' '},
                  {loca: 'he',name: 'Hebrew (עברית)',flag: ' '},
                  {loca: 'hr',name: 'Croatian (hrvatski jezik)',flag: ' '},
                  {loca: 'hu',name: 'Hungarian (magyar)',flag: ' '},
                  {loca: 'id',name: 'Indonesian (Indonesian)',flag: ' '},
                  {loca: 'it',name: 'Italian (Italiano)',flag: ' '},
                  {loca: 'ja',name: 'Japanese (日本語)',flag: ' '},
                  {loca: 'ko',name: 'Korean (한국어)',flag: ' '},
                  {loca: 'lt',name: 'Lithuanian (lietuvių kalba)',flag: ' '},
                  {loca: 'lv',name: 'Latvian (latviešu valoda)',flag: ' '},
                  {loca: 'nl',name: 'Dutch (Nederlands)',flag: ' '},
                  {loca: 'no',name: 'Norwegian (Norsk)',flag: ' '},
                  {loca: 'pl',name: 'Polish (język polski)',flag: ' '},
                  {loca: 'pt',name: 'Portuguese (Português)',flag: ' '},
                  {loca: 'ro',name: 'Romanian (Română)',flag: ' '},
                  {loca: 'ru',name: 'Russian (Русский)',flag: ' '},
                  {loca: 'sk',name: 'Slovak (slovenčina)',flag: ' '},
                  {loca: 'sl',name: 'Slovene (slovenski jezik)',flag: ' '},
                  {loca: 'srCyrl',name: 'Serbian (српски језик)',flag: ' '},
                  {loca: 'srLatn',name: 'Serbian (srpski jezik)',flag: ' '},
                  {loca: 'sv',name: 'Swedish (svenska)',flag: ' '},
                  {loca: 'th',name: 'Thai (ไทย)',flag: ' '},
                  {loca: 'tr',name: 'Turkish (Türkçe)',flag: ' '},
                  {loca: 'uk',name: 'Ukrainian (Українська)',flag: ' '},
                  {loca: 'vi',name: 'Vietnamese (Tiếng Việt)',flag: ' '},
                  {loca: 'zhHans',name: 'Chinese (中文)',flag: ' '},
                  {loca: 'zhHant',name: 'Chinese (正體中文)',flag: ' '},



    return {isos: [ 'af', 'ar', 'az', 'bg', 'ca', 'cs', 'de', 'el', 'en', 'es', 'et', 'fa', 'fi', 'fr','he', 'hr', 'hu', 'id', 'it', 'ja', 'ko', 'lt', 'lv', 'nl', 'no', 'pl', 'pt', 'ro',
			'ru', 'sk', 'sl', 'sv', 'th', 'tr', 'uk', 'ckb', 'srCyrl', 'zhHans', 'zhHant' ],
            langitems:['Afrikaans (Afrikaans)','Arabic (اللغة العربية)','Catalan (català)',
                'Czech (čeština)', 'German (Deutsch)', 'Greek (Ελληνικά)','English',
                'Spanish (Español)','Persian (فارسی)','Finnish (suomi)','French (Français)',
                'Hebrew (עברית)','Croatian (hrvatski jezik)','Hungarian (magyar)',
                'Indonesian (Indonesian)','Italian (Italiano)','Japanese (日本語)','Korean ()',
                'Lithuanian (lietuvių kalba)','Latvian (latviešu valoda)','Dutch (Nederlands)',
                'Norwegian (Norsk)','Polish (język polski)','Portuguese (Português)',
                'Romanian (Română)', 'Russian (Русский)','Slovak (slovenčina)','Slovene (slovenski jezik)',
                'Serbian (српски језик)','Swedish (svenska)','Thai (ไทย)','Turkish (Türkçe)',
                'Ukrainian (Українська)','Chinese (中文)'
               ],
               flags: [ 'ZA', 'AE', 'AD', 'CZ', 'DE', 'GR', 'GB', 'ES', 'IR', 'FI', 'FR', 'IL',
                        'HR', 'HU', 'ID', 'IT', 'JP', 'KR', 'LT', 'LV', 'NL', 'NO', 'PL', 'PT',
                        'RO', 'RU', 'SK', 'SI', 'RS', 'SE', 'TH', 'TR', 'UA', 'CN'
               ],

